apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-monitor
  labels:
    app: simple-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-monitor
  template:
    metadata:
      labels:
        app: simple-monitor
    spec:
      containers:
      - name: monitor
        image: curlimages/curl:latest
        command:
        - /bin/sh
        - -c
        - |
          while true; do
            echo "$(date) - Running health checks..."
            
            # Check web service
            WEB_STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://web-service)
            if [ "$WEB_STATUS" = "200" ]; then
              echo "Web service is UP (Status: $WEB_STATUS)"
            else
              echo "ALERT: Web service is DOWN (Status: $WEB_STATUS)"
              # In a real environment, you would send an alert here
            fi
            
            # Check API service
            API_STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://api-service:5001/test)
            if [ "$API_STATUS" = "200" ]; then
              echo "API service is UP (Status: $API_STATUS)"
            else
              echo "ALERT: API service is DOWN (Status: $API_STATUS)"
              # In a real environment, you would send an alert here
            fi
            
            echo "Health check completed. Sleeping for 60 seconds..."
            sleep 60
          done
---
apiVersion: v1
kind: Service
metadata:
  name: monitor-service
spec:
  selector:
    app: simple-monitor
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP