apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: face-detection-app-alerts
  namespace: monitoring
  labels:
    release: prometheus
spec:
  groups:
  - name: face-detection-app.rules
    rules:
    - alert: HighAPILatency
      expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{service="api-service"}[5m])) by (le)) > 0.5
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High API latency detected"
        description: "API latency is above 500ms for 95th percentile."
    
    - alert: APIHighErrorRate
      expr: sum(rate(http_requests_total{service="api-service",status=~"5.."}[5m])) / sum(rate(http_requests_total{service="api-service"}[5m])) > 0.05
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "High API error rate"
        description: "Error rate is above 5% for API service."
    
    - alert: WebHighErrorRate
      expr: sum(rate(http_requests_total{service="web-service",status=~"5.."}[5m])) / sum(rate(http_requests_total{service="web-service"}[5m])) > 0.05
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "High Web error rate"
        description: "Error rate is above 5% for Web service."
    
    - alert: PodCrashLooping
      expr: rate(kube_pod_container_status_restarts_total{namespace="default",pod=~"api-deployment.*|web-deployment.*"}[5m]) > 0.2
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "Pod is crash looping"
        description: "Pod {{ $labels.pod }} is crash looping."
    
    - alert: MemoryUsageHigh
      expr: container_memory_usage_bytes{namespace="default",pod=~"api-deployment.*|web-deployment.*"} / container_spec_memory_limit_bytes{namespace="default",pod=~"api-deployment.*|web-deployment.*"} > 0.85
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: "High memory usage"
        description: "Container {{ $labels.container }} in pod {{ $labels.pod }} is using {{ $value | humanizePercentage }} of its memory limit."