prometheus:
  service:
    type: LoadBalancer

grafana:
  service:
    type: LoadBalancer
  adminPassword: admin
  
alertmanager:
  config:
    route:
      group_by: ["alertname", "job"]
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: teams
    receivers:
      - name: teams
        webhook_configs:
          - url: "${TEAMS_WEBHOOK}"
            send_resolved: true